### ISSUE TITLE
gradient overlay when images are uploaded for the background of the pullquote card

### ISSUE THREAD

**Issue by helgalivsalinas** [seattletimes/pullquote#4]

**Comment by thomaswilburn** [comment]
Can you provide an example? I want to make sure I understand what you actually want for this.

**Comment by helgalivsalinas** [comment]
Like the image in this tweet. It has a dark transparent overlay on top of the image that makes it easier for the text to be read. 

https://twitter.com/latimes/status/743888532045971456

![latimes_gradient](https://cloud.githubusercontent.com/assets/6556562/16166073/cd16699a-349c-11e6-9f17-54045a4c7019.jpg)

**Comment by thomaswilburn** [comment]
I think my instinct is to say that there's a limit to the sophistication I think this should offer--if you want that kind of thing (or, for example, the mixed fonts that are on this example, which requires additional markup capability), you should really just be using Photoshop.
